#!/usr/bin/env python3
# -*- coding = utf-8 -*-
"""
Utility methods for accessing the Quandl finance API.

A mid-level module, since the tools here are used only by
the research methods in the `finance` subdirectory.
"""
import os
import json
import logging

import pandas as pd
import matplotlib.pyplot as plt

import quandl

def _configure_api():
   """Loads the API key and configures the API at the start."""
   # Load the API key from the JSON file.
   with open(os.path.join(os.path.dirname(__file__), 'secrets.json'), 'r') as json_file:
      API_KEY = json.load(json_file)['QUANDL_API_KEY']

   # Configure the API.
   quandl.ApiConfig.api_key = API_KEY

if __name__ == '__main__':
   # If running this file directly, then user is debugging.
   logging.basicConfig(format = '%(levelname)s - %(name)s: %(message)s')

   # Warn the user that they are in debugging mode.
   logging.warning("You are now directly running the finance.data file. Unless you are debugging, do not edit this file.")

   # Configure the API.
   _configure_api()

   # WORKING CODE HERE:
   data = quandl.get_table('ZACKS/FC', paginate = True, ticker = ['MSFT'])

   print(data)

else:
   # Set up logging configuration for the InformationLoader class.
   logging.basicConfig(format = '%(levelname)s - %(name)s: %(message)s')

   # Otherwise, something is being imported. In that case, configure the API.
   _configure_api()


