#!/usr/bin/env python3
# -*- coding = utf-8 -*-
# Copyright 2021 Amogh Joshi. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Utility methods for accessing the Quandl finance API.

A mid-level module, since the tools here are used only by
the research methods in the `finance` subdirectory.
"""
import os
import json
import logging

import pandas as pd
import matplotlib.pyplot as plt

import quandl

def _configure_api():
   """Loads the API key and configures the API at the start."""
   # Load the API key from the JSON file.
   with open(os.path.join(os.path.dirname(__file__), 'secrets.json'), 'r') as json_file:
      API_KEY = json.load(json_file)['QUANDL_API_KEY']

   # Configure the API.
   quandl.ApiConfig.api_key = API_KEY

if __name__ == '__main__':
   # If running this file directly, then user is debugging.
   logging.basicConfig(format = '%(levelname)s - %(name)s: %(message)s')

   # Warn the user that they are in debugging mode.
   logging.warning("You are now directly running the finance.data file. Unless you are debugging, do not edit this file.")

   # Configure the API.
   _configure_api()

   # WORKING CODE HERE:
   data = quandl.get_table('ZACKS/FC', paginate = True, ticker = ['MSFT'])

   print(data)

else:
   # Set up logging configuration for the InformationLoader class.
   logging.basicConfig(format = '%(levelname)s - %(name)s: %(message)s')

   # Otherwise, something is being imported. In that case, configure the API.
   _configure_api()


